Fix NoneType in fake promoter computation
Traceback (most recent call last):
  File "/Users/cdparra/Projects/participa/politic-bots/src/bot_detector/bot_detector.py", line 364, in <module>
    bot_detector.compute_fake_promoter_heuristic([])
  File "/Users/cdparra/Projects/participa/politic-bots/src/bot_detector/bot_detector.py", line 268, in compute_fake_promoter_heuristic
    'value': fp
TypeError: 'NoneType' object does not support item assignment